In [1]:
import numpy as np

# 1: Create a 3x3x3 array with random values

In [6]:
# we need to create a 3x3x3 array with random values

arr1 =  np.random.randint(1, 100, size = (3, 3, 3))
print(arr1)

[[[49 60 46]
  [16 91 47]
  [91 72 69]]

 [[64 64 64]
  [28 78 60]
  [56 11 83]]

 [[61 15 39]
  [97 59 92]
  [36 36  7]]]


# 2: Create a 5x5 matrix with  values 1, 2, 3, 4 just below the diagonal

In [14]:
#  a matrix with 5x5 grid and the values should be 1, 2, 3, 4 below the diagonals

# take the values as a set
val = [1, 2, 3, 4]

mat = np.zeros((5, 5), dtype = int)
# print(mat)
# print("\n")
for i in range(1, 5):
    mat[i, i-1] = val[i-1]
print(mat)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3: Create a 8x8 matrix and fill it with a checkerboard pattern

In [18]:
# check board as alternative cells have same color 
# and adjacent cells have different color

board = np.zeros((8, 8), dtype=int)

board[1::2, ::2] = 1
board[::2, 1::2] = 1

print(board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4: Normalize a 5x5 random matrix


In [22]:
mat = np.random.randint(1, 100, size = (5, 5))

mean = mat.mean()
std_dev = mat.std()

# normalize the matrix formula (mat-mean)/sd

normalized_mat = (mat - mean) / std_dev

print("Original random matrix:")
print(mat)
print("\nNormalized matrix:")
print(normalized_mat)


Original random matrix:
[[16 75 98 76 63]
 [56  7 97 92 44]
 [11 29 41 99 33]
 [84 94 60 78 70]
 [24 19 14 78 24]]

Normalized matrix:
[[-1.27766926  0.64143681  1.3895629   0.67396403  0.25111015]
 [ 0.0234196  -1.57041425  1.35703568  1.19439957 -0.36690706]
 [-1.44030536 -0.85481538 -0.46448872  1.42209012 -0.72470649]
 [ 0.9341818   1.25945401  0.15352848  0.73901847  0.4788007 ]
 [-1.01745148 -1.18008759 -1.3427237   0.73901847 -1.01745148]]


# 5: How to find common values between two arrays?

In [24]:
n = int(input("Enter the size of the arrays: "))
arr1 = []
arr2 = []

arr1 = [int(ele) for ele in (input(f"Enter the {n} elements in to the arr1: ").split())]
arr2 = [int(ele) for ele in (input(f"Enter the {n} elements in to the arr2: ").split())]


array1 = np.array(arr1)
array2 = np.array(arr2)

cmn_vals = np.intersect1d(array1, array2)

print("Common values between array1 and array2:")
print(cmn_vals)


Enter the size of the arrays: 10
Enter the 10 elements in to the arr1: 3 4 29 12 20 65 38 89 24 55
Enter the 10 elements in to the arr2: 7 8 90 23 29 24 3 12 89 5 22
Common values between array1 and array2:
[ 3 12 24 29 89]


# 6: How to get the dates of yesterday, today and tommorow?

In [31]:
from datetime import datetime, timedelta

today = datetime.now()

# if we need yesterday we have to do -1 if tomorrow we have to do +1 for today 
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

today_np = np.datetime64(today)
yesterday_np = np.datetime64(yesterday)
tomorrow_np = np.datetime64(tomorrow)


print("\nNumPy Datetime Objects:")
print("Yesterday\t: ", yesterday_np)
print("Today\t\t: ", today_np)
print("Tomorrow\t: ", tomorrow_np)



NumPy Datetime Objects:
Yesterday	:  2023-09-20T15:26:18.019541
Today		:  2023-09-21T15:26:18.019541
Tomorrow	:  2023-09-22T15:26:18.019541


# 7: Consider two random arrayA and arrqayB, check if they are equal

In [39]:
n = int(input("Enter the size of the array: "))
arr1 =np.random.randint(1, 20, n)
arr2 = np.random.randint(1, 20, n)

print(f"array1: {arr1}\n")
print(f"array2: {arr2}\n")
flag = np.array_equal(arr1, arr2)
if flag:
    print("Both the arrays are equal")
else:
    print("Both array are not equal")


Enter the size of the array: 10
array1: [ 6  1 18 15 14 10 19  4 12  4]

array2: [18  3  9  3  3  6  5 18 17  3]

Both array are not equal


# 8: Crreate random vector of size 10 and replace the maximum value by 0

In [48]:
random_vec = np.random.randint(1,100, 10)
print(f"Random vector\t\t: {random_vec}")
maxi = np.argmax(random_vec)

print(f"maximum element \t: {random_vec[maxi]}")
random_vec[maxi] = 0

# print("Random Vector with Maximum Value Replaced:")
print(f"replaced with zero\t: {random_vec}")

Random vector		: [56 14 19 44 21 43 59 71 24 51]
maximum element 	: 71
replaced with zero	: [56 14 19 44 21 43 59  0 24 51]


# 9: How to print all the values of an array?

In [55]:
arr = np.random.randint(1, 100, 15)
for ele in arr:
    print(ele, end=" ")

62 72 59 32 72 74 86 68 19 71 47 46 55 60 31 

# 10: Subtract the mean of each row of matrix

In [63]:
mat = np.random.randint(1, 50, size = (5, 5))

row_means = np.mean(mat, axis=1, keepdims=True)

matrix_means = mat - row_means
print(f"Means:\n {row_means}\n")
print(f"Original Matrix:\n{mat}\n")
print(f"\nMatrix after subtracting row means:\n{matrix_means}\n")
print()

Means:
 [[20.6]
 [31.2]
 [16.6]
 [29. ]
 [22.8]]

Original Matrix:
[[ 2 49 34 12  6]
 [45 27 25 38 21]
 [10 28 10 31  4]
 [27  9 31 31 47]
 [ 4  5 36 26 43]]


Matrix after subtracting row means:
[[-18.6  28.4  13.4  -8.6 -14.6]
 [ 13.8  -4.2  -6.2   6.8 -10.2]
 [ -6.6  11.4  -6.6  14.4 -12.6]
 [ -2.  -20.    2.    2.   18. ]
 [-18.8 -17.8  13.2   3.2  20.2]]




# 11: Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [66]:
n = int(input("Enter the size of the vector: "))
arr = [int(ele) for ele in(input(f"Enter {n} elements in to the: ").split())]

arr2 = [int(ele) for ele in(input(f"Ente the indices values where +1 want: ").split())]

arr1 = np.array(arr)
arr2 = np.array(arr2)

index = np.unique(arr2)
arr1[arr2] += 1

print(f"After +1 for \n{arr}\n\non indices of\n\n{arr2}\n\nthe result array is \n{arr1}")

Enter the size of the vector: 5
Enter 5 elements in to the: 87 34 86 234 1267
Ente the indices values where +1 want: 0 2 4
After +1 for 
[87, 34, 86, 234, 1267]

on indices of

[0 2 4]

the result array is 
[  88   34   87  234 1268]


# 12: How to get the diagonal of a dot product?

In [70]:
# let us take two matrices

mat1 = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

mat2= np.array([[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]])

mat_dot = np.dot(mat1, mat2)

diag_values = np.diag(mat_dot)
print(f"\n{mat1}\n\n{mat2}\n\n")
print(f"Dot Product Matrix:\n\n{mat_dot}")
print(f"\nDiagonal Elements of Dot Product:\n\n{diag_values}")



[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[10 11 12]
 [13 14 15]
 [16 17 18]]


Dot Product Matrix:

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]

Diagonal Elements of Dot Product:

[ 84 216 366]


# 13: How to find the most frequent value in an array?
	x = np.random.randint(0, 10, 50)

In [72]:
x = np.random.randint(0, 10, 50)

cnt = np.bincount(x)

maxi = np.argmax(cnt)

print(f"Array: \n{x}\n\n")
print(f"Most frequent element in the array is:\n{maxi} ")

Array: 
[1 9 3 0 5 5 9 9 5 0 3 4 8 9 7 7 4 5 7 5 2 0 2 2 4 0 4 2 4 7 1 5 1 3 2 2 2
 6 4 6 2 1 7 2 5 5 7 0 2 3]


Most frequent element in the array is:
2 


# 14: how to get the n largest values of an array

In [78]:
n = int(input("Enter the number of largest elements needed: "))

arr = np.random.randint(1, 100, 15)

values = np.partition(arr, -n)[-n:]
print(f"The array is \t\t: {arr}")
print(f"largest {n} elements are\t: {values}")

Enter the number of largest elements needed: 5
The array is 		: [ 5 38 51 39 81 69 60 97 16 50 61 98 89 10  3]
largest 5 elements are	: [69 81 89 97 98]


# 15: how to create a record array from a regular array?

In [91]:

regular = [(1, "Chandu", 30),
           (2, "Jagadeesh", 40),
           (3, "Michael", 50)]

datatype = [("ID", int), ("Name", 'U10'), ("Age", int)]

structured_array = np.array(regular, dtype=datatype)

print("Structured Array:")
print(structured_array)

print("\nElements by Field Name:")
print("ID\t:", structured_array['ID'])
print("Name\t:", structured_array['Name'])
print("Age\t:", structured_array['Age'])


Structured Array:
[(1, 'Chandu', 30) (2, 'Jagadeesh', 40) (3, 'Michael', 50)]

Elements by Field Name:
ID	: [1 2 3]
Name	: ['Chandu' 'Jagadeesh' 'Michael']
Age	: [30 40 50]


# 16: How to swap two rows of an array?

In [97]:
arr = np.array([[1, 2, 2, 4],
                [11, 12, 13, 14],
                [21, 22, 23 ,24],
                [31, 32, 33, 34]])

print(f"Before Swapping:\n\n{arr}")
temp = arr[0].copy()
arr[0] = arr[2]
arr[2] = temp

print(f"\nAfter Swapping:\n\n{arr}")


Before Swapping:

[[ 1  2  2  4]
 [11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]

After Swapping:

[[21 22 23 24]
 [11 12 13 14]
 [ 1  2  2  4]
 [31 32 33 34]]


# 17: Write python code to reshape to the next dimension of numpy array?
	x = np.array([[23, 34, 121], [23, 22, 67], [686, 434, 123]])

In [99]:
x = np.array([[23, 34, 121], 
              [23, 22, 67], 
              [686, 434, 123]])

print(f"Before Re-shaping:\n\n{x}\n")
x = x.reshape(x.shape[0], x.shape[1], 1)
print(x)

Before Re-shaping:

[[ 23  34 121]
 [ 23  22  67]
 [686 434 123]]

[[[ 23]
  [ 34]
  [121]]

 [[ 23]
  [ 22]
  [ 67]]

 [[686]
  [434]
  [123]]]
